version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: blitzchess-db
    restart: always
    environment:
      POSTGRES_USER: bc
      POSTGRES_PASSWORD: bc
      POSTGRES_DB: blitzchess
    ports:
      - "5432:5432"
    volumes:
      - blitzchess_pg_data:/var/lib/postgresql/data

volumes:
  blitzchess_pg_data:
